### ISSUE TITLE
构建的时候出问题了呢

### ISSUE THREAD

**Issue by Beennnx** [hyperf-cloud/hyperf-docker#1]
The command '/bin/sh -c composer install --no-dev     && composer dump-autoload -o     && php /opt/www/bin/hyperf.php di:init-proxy' returned a non-zero code: 1

**Comment by limingxinleo** [comment]
你是否构建了根目录那个Docker，那个需要配合项目文件一起使用的

https://github.com/hyperf-cloud/hyperf-skeleton/blob/master/Dockerfile

**Comment by Beennnx** [comment]
直接在链接里面那个项目构建docker就可以了啊

**Comment by limingxinleo** [comment]
对的。。issue我先关闭了。如果还有问题，你再打开
